/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "rcc.h"
#include "spi.h"
#include "gpio.h"

#define APB2    0x40023844
#define AHB1    0x40023830
int main(void)
{
	uint8_t spiData[2];
	spiData[0] = 0x00;
	Spi::SPI_t *spi1 = (Spi::SPI_t*)0x40013000;
	spi1->spi_config(APB2, AHB1);

	spi1->toggle_ss();
	spi1->transmit(spiData, 1);

    /* Loop forever */
	for(;;);
}
